sonar.projectKey=khorner_sonar-demo
sonar.organization=khorner
sonar.projectName=Sonar Demo
sonar.sources=.
sonar.exclusions=.github/**
sonar.newCode.referenceBranch=main
sonar.scm.exclusions.disabled=true